[package]
name = "sorted_collections"
version = "0.0.1"
authors = ["Galen O'Sullivan <galenosullivan@gmail.com>"]
license = "Apache-2.0"

[dependencies]

[dev-dependencies]
rand = "0.6"
quickcheck = "0.8.2"
